#server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5433/financialhealth
    platform: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      dll-auto: update
    database: postgresql

#SecretKey JWT
auth:
  jwt:
    secret: DanielaVeigaViana@82.OliviaVianaValerio@22.DaniloValerioSilva@86

  #1 dia em milliseconds 86400000
  jwt-expiration-millisec: 86400000

