#server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/financialhealth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
